package com.cbt.dao;

import com.cbt.entity.QuoteReportType;
import com.cbt.entity.QuoteWeeklyReport;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface QuoteReportTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int insert(QuoteReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int insertSelective(QuoteReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    QuoteReportType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int updateByPrimaryKeySelective(QuoteReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int updateByPrimaryKey(QuoteReportType record);



    /**
     * 根据询盘号或者项目号查询报告
     * @param csgOrderId
     * @param
     * @param
     * @return
     */
    List<QuoteReportType> queryByOrderId(@Param("csgOrderId")String csgOrderId,@Param("orderId")Integer orderId);

    /**
     * 根据工厂id询盘号或者项目号查询报告
     * @param csgOrderId
     * @param
     * @param
     * @return
     */
    List<QuoteReportType> queryByOrderIdAndFactoryId(@Param("csgOrderId")String csgOrderId,@Param("orderId")Integer orderId,@Param("factoryId")String factoryId);


    /**
     * 根据项目号和阶段查询当前报告
     * @param csgOrderId
     * @param orderId
     * @param projectStage
     * @return
     */
    List<QuoteReportType> selectByOrderIdAndStage(@Param("csgOrderId")String csgOrderId,@Param("orderId")Integer orderId,@Param("projectStage")Integer projectStage);

}