package com.cbt.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class QuoteReportType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_report_type.id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    private Integer id;               //id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_report_type.order_id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    private Integer orderId;         //询盘号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_report_type.create_date
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    private String createDate;         //创建时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_report_type.remark
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    private String remark;           //备注信息

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_report_type.csg_order_id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    private String csgOrderId;       //内部项目号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quote_report_type.project_stage
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    private Integer projectStage;     //项目阶段

    private String factoryId;         //上传工厂id

    //虚拟字段
    private List<QuoteWeeklyReport> reportList;     //报告列表

    private int picCount;             //图片个数
    private int fileCount;            //文件个数
    private int videoCount;           //视频个数


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    public String getFactoryId() {
        return factoryId;
    }

    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    public int getPicCount() {
        return picCount;
    }

    public void setPicCount(int picCount) {
        this.picCount = picCount;
    }

    public int getFileCount() {
        return fileCount;
    }

    public void setFileCount(int fileCount) {
        this.fileCount = fileCount;
    }

    public int getVideoCount() {
        return videoCount;
    }

    public void setVideoCount(int videoCount) {
        this.videoCount = videoCount;
    }

    public List<QuoteWeeklyReport> getReportList() {
        return reportList;
    }

    public void setReportList(List<QuoteWeeklyReport> reportList) {
        this.reportList = reportList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_report_type.id
     *
     * @return the value of quote_report_type.id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_report_type.id
     *
     * @param id the value for quote_report_type.id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_report_type.order_id
     *
     * @return the value of quote_report_type.order_id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_report_type.order_id
     *
     * @param orderId the value for quote_report_type.order_id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_report_type.create_date
     *
     * @return the value of quote_report_type.create_date
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_report_type.create_date
     *
     * @param createDate the value for quote_report_type.create_date
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_report_type.remark
     *
     * @return the value of quote_report_type.remark
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_report_type.remark
     *
     * @param remark the value for quote_report_type.remark
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_report_type.csg_order_id
     *
     * @return the value of quote_report_type.csg_order_id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public String getCsgOrderId() {
        return csgOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_report_type.csg_order_id
     *
     * @param csgOrderId the value for quote_report_type.csg_order_id
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public void setCsgOrderId(String csgOrderId) {
        this.csgOrderId = csgOrderId == null ? null : csgOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quote_report_type.project_stage
     *
     * @return the value of quote_report_type.project_stage
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public Integer getProjectStage() {
        return projectStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quote_report_type.project_stage
     *
     * @param projectStage the value for quote_report_type.project_stage
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    public void setProjectStage(Integer projectStage) {
        this.projectStage = projectStage;
    }


    @Override
    public String toString() {
        return "QuoteReportType{" +
                "id=" + id +
                ", orderId=" + orderId +
                ", createDate='" + createDate + '\'' +
                ", remark='" + remark + '\'' +
                ", csgOrderId='" + csgOrderId + '\'' +
                ", projectStage=" + projectStage +
                ", factoryId='" + factoryId + '\'' +
                ", reportList=" + reportList +
                ", picCount=" + picCount +
                ", fileCount=" + fileCount +
                ", videoCount=" + videoCount +
                '}';
    }
}