package com.cbt.service;

import com.cbt.entity.QuoteReportType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface QuoteReportTypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int insert(QuoteReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int insertSelective(QuoteReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    QuoteReportType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int updateByPrimaryKeySelective(QuoteReportType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quote_report_type
     *
     * @mbggenerated Mon Oct 29 10:02:43 CST 2018
     */
    int updateByPrimaryKey(QuoteReportType record);



    /**
     * 根据询盘号或者项目号查询报告
     * @param csgOrderId
     * @param
     * @param
     * @return
     */
    List<QuoteReportType> queryByOrderId(String csgOrderId,Integer orderId);
    /**
     * 根据工厂id询盘号或者项目号查询报告
     * @param csgOrderId
     * @param
     * @param
     * @return
     */
    List<QuoteReportType> queryByOrderIdAndFactoryId(String csgOrderId,Integer orderId,String factoryId);



    /**
     * 根据项目号和阶段查询当前报告
     * @param csgOrderId
     * @param orderId
     * @param projectStage
     * @return
     */
    List<QuoteReportType> selectByOrderIdAndStage(String csgOrderId,Integer orderId,Integer projectStage);


}